name: "Frogbot Scan Pull Request"
on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  id-token: write
  security-events: write
  pull-requests: write
  contents: read
jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    # A pull request needs to be approved, before Frogbot scans it. Any GitHub user who is associated with the
    # "frogbot" GitHub environment can approve the pull request to be scanned.
    environment: frogbot
    steps:
      # Install prerequisites
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - uses: jfrog/frogbot@v2
        env:
          # [Mandatory]
          # JFrog platform URL (This functionality requires version 3.29.0 or above of Xray)
          JF_URL: https://${{ vars.JF_HOST }}/
          JF_GIT_AGGREGATE_FIXES: "TRUE"
          # Displays all existing vulnerabilities, including the ones that were added by the pull request.
          JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"          
          # [Mandatory]
          # The GitHub token automatically generated for the job
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_DEPS_REPO: "dro-npm-unsecure-remote"
          # [Optional, default: "TRUE"]
          # Fails the Frogbot task if any security issue is found.
          #JF_FAIL: "FALSE" 
        with:
          oidc-provider-name: davidro-github-integration
          oidc-audience: davidro-github